server:
  port: 8080

---

spring:
  profiles: default
  datasource:
    url: jdbc:mariadb://localhost:3306/tatadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1235
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: member
          destination: coupon
          contentType: application/json
        event-out:
          destination: coupon
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8081

api:
  coupon:
    url: http://localhost:8082
  cancellation:
    url: http://localhost:8086
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: member
          destination: coupon
          contentType: application/json
        event-out:
          destination: coupon
          contentType: application/json